name: Docker CI

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and Push the Image to GHCR
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} \
          -p ${{ github.token }}
          docker build . --file Dockerfile --tag ghcr.io/${{ OWNER_LC }}/puzzling-logic:latest
          docker push ghcr.io/${{ OWNER_LC }}/puzzling-logic:latest
