name: Docker CI

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and Push the Image to GHCR
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} \
          -p ${{ secrets.PAT }}
          docker build . --file Dockerfile --tag ghcr.io/aurux/puzzling-logic:latest
          docker push ghcr.io/aurux/puzzling-logic:latest
